apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django-messaging-app
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: "1.0"
    spec:
      containers:
      - name: django-app
        image: messaging-app:latest
        imagePullPolicy: Never  # Use local image built with Docker
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "True"
        - name: SECRET_KEY
          value: "django-insecure-k8s-secret-key-change-in-production"
        - name: DB_ENGINE
          value: "django.db.backends.sqlite3"
        - name: DB_NAME
          value: "/app/db.sqlite3"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-storage
          mountPath: /app/data
      volumes:
      - name: app-storage
        emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: django-messaging-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django-messaging-app
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: "django.db.backends.sqlite3"
